### ISSUE TITLE
Installation of dependencies ... needs a little documentation

### ISSUE THREAD

**Issue by sam1ee** [Spationaute/FullEarth#1]
Glew, opengl, curl -- I have all installed but installation fails.
possible solution: build dependencies from source:
Glew: https://github.com/nigels-com/glew
Curl: https://github.com/curl/curl
opengl: https://www.howtoforge.com/tutorial/how-to-install-openssl-from-source-on-linux

**Comment by Spationaute** [comment]
I added more information on the dependencies.

**Comment by sam1ee** [comment]
I must have missed a dependency. I added libcurl4-openssl-dev
I still can't get make to work. I will try your precompiled version
