### ISSUE TITLE
Curl errors

### ISSUE THREAD

**Issue by sam1ee** [Spationaute/FullEarth#2]
/usr/bin/cmake: /usr/local/lib/libcurl.so.4: no version information available (required by /usr/bin/cmake)

This is fixed by this:
https://stackoverflow.com/questions/30017397/error-curl-usr-local-lib-libcurl-so-4-no-version-information-available-requ

**Comment by Spationaute** [comment]
I think it is more a problem with your current installation (has suggested by the fix). Still the first solution you provided will solve this also.

**Comment by sam1ee** [comment]
The version of cURL you suggest has some major security flaws
https://curl.haxx.se/docs/vuln-7.58.0.html

**Comment by Spationaute** [comment]
I'm at my desktop at work. I used the library I had has reference, its an older installation. The latest version of curl work, I used it at home. I will update the version to the latest on the README page. Also, the software use just HTTPS and not the protocol concerned.

**Comment by sam1ee** [comment]
ditto

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10
